[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "52FBC8SyRo1ZoE5vFY7qcu3EePgKeLRhquxcGeetUCL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
